drop table hmdapub2009;
drop table hmdapub2010;
drop table hmdapub2011;
drop table hmdapub2012;
drop table hmdapub2013;


CREATE TABLE HMDApub2009
(
	AsOfDate varchar(4),
	RespondentID varchar(10),
	RespondentName varchar(60),
	AgencyCode varchar(1),
	LoanType varchar(1),
	PropertyType varchar(1),
	LoanPurpose varchar(1),
	Occupancy varchar(1),
	LoanAmount varchar(8),
	PreApprovals varchar(1),
	ActionType varchar(1),
	MSAOfProperty varchar(5),
	StateCode varchar(2),
	StateName varchar(15),
	CountyCode varchar(3),
	CountyName varchar(60),
	CensusTractNumber varchar(7),
	ApplicantEthnicity varchar(1),
	CoApplicantEthnicity varchar(1),
	ApplicantRace1 varchar(1),
	ApplicantRace2 varchar(1),
	ApplicantRace3 varchar(1),
	ApplicantRace4 varchar(1),
	ApplicantRace5 varchar(1),
	CoApplicantRace1 varchar(1),
	CoApplicantRace2 varchar(1),
	CoApplicantRace3 varchar(1),
	CoApplicantRace4 varchar(1),
	CoApplicantRace5 varchar(1),
	ApplicantSex varchar(1),
	CoApplicantSex varchar(1),
	ApplicantIncome varchar(4),
	PurchaserType varchar(1),
	DenialReason1 varchar(1),
	DenialReason2 varchar(1),
	DenialReason3 varchar(1),
	RateSpread varchar(5),
	HOEPAStatus varchar(1),
	LienStatus varchar(1),
	Area_Population varchar(20),
	Minority_Population_pct varchar(6),
	HUD_Median_Family_Incom varchar(10),
	Tract_to_MSA_MD_Income varchar(15),
	Num_of_Owner_occupied_units varchar(8),
	Num_of_1_to_4_Family_units varchar(8),
	Application_date_indicator varchar(1),
	FipsCode varchar(12),
	Latitude decimal(18,8),
	Longitude decimal(18,8)
);



CREATE TABLE HMDApub2010
(
	AsOfDate varchar(4),
	RespondentID varchar(10),
	RespondentName varchar(60),
	AgencyCode varchar(1),
	LoanType varchar(1),
	PropertyType varchar(1),
	LoanPurpose varchar(1),
	Occupancy varchar(1),
	LoanAmount varchar(8),
	PreApproval varchar(1),
	ActionType varchar(1),
	MSAOfProperty varchar(5),
	StateCode varchar(2),
	StateName varchar(2),
	CountyCode varchar(3),
	CountyName varchar(50),
	CensusTractNumber varchar(7),
	ApplicantEthnicity varchar(1),
	CoApplicantEthnicity varchar(1),
	ApplicantRace1 varchar(1),
	ApplicantRace2 varchar(1),
	ApplicantRace3 varchar(1),
	ApplicantRace4 varchar(1),
	ApplicantRace5 varchar(1),
	CoApplicantRace1 varchar(1),
	CoApplicantRace2 varchar(1),
	CoApplicantRace3 varchar(1),
	CoApplicantRace4 varchar(1),
	CoApplicantRace5 varchar(1),
	ApplicantSex varchar(1),
	CoApplicantSex varchar(1),
	ApplicantIncome varchar(4),
	PurchaserType varchar(1),
	DenialReason1 varchar(1),
	DenialReason2 varchar(1),
	DenialReason3 varchar(1),
	RateSpread varchar(5),
	HOEPAStatus varchar(1),
	LienStatus varchar(1),
	AreaPopulation varchar(10),
	MinorityPopulationPct varchar(6),
	HUD_Median_Family_Income varchar(8),
	Tract_to_MSA_MD_Income varchar(6),
	Num_of_Owner_occupied_units varchar(8),
	Num_of_1_to_4_Family_units varchar(8),
	Application_Date_Indicator varchar(1),
	FipsCode varchar(12),
	Latitude decimal(18,8),
	Longitude decimal(18,8)
);


CREATE TABLE HMDApub2011
(
	AsOfDate varchar(4),
	RespondentID varchar(10),
	RespondentName varchar(60),
	AgencyCode varchar(1),
	LoanType varchar(1),
	PropertyType varchar(1),
	LoanPurpose varchar(1),
	Occupancy varchar(1),
	LoanAmount varchar(8),
	Preapproval varchar(1),
	ActionType varchar(1),
	MSAOfProperty varchar(5),
	StateCode varchar(2),
	StateName varchar(20),
	CountyCode varchar(3),
	CountyName varchar(50),
	CensusTractNumber varchar(7),
	ApplicantEthnicity varchar(1),
	CoApplicantEthnicity varchar(1),
	ApplicantRace1 varchar(1),
	ApplicantRace2 varchar(1),
	ApplicantRace3 varchar(1),
	ApplicantRace4 varchar(1),
	ApplicantRace5 varchar(1),
	CoApplicantRace1 varchar(1),
	CoApplicantRace2 varchar(1),
	CoApplicantRace3 varchar(1),
	CoApplicantRace4 varchar(1),
	CoApplicantRace5 varchar(1),
	ApplicantSex varchar(1),
	CoApplicantSex varchar(1),
	ApplicantIncome varchar(4),
	PurchaserType varchar(1),
	DenialReason1 varchar(1),
	DenialReason2 varchar(1),
	DenialReason3 varchar(1),
	RateSpread varchar(5),
	HOEPAStatus varchar(1),
	LienStatus varchar(1),
	AreaPopulation varchar(10),
	MinorityPopulationPct varchar(6),
	HUD_Median_Family_Income varchar(8),
	Tract_to_MSA_MD_Income varchar(6),
	Num_of_Owner_occupied_units varchar(8),
	Num_of_1_to_4_Family_units varchar(8),
	Application_Date_Indicator varchar(1),
	FipsCode varchar(12),
	Latitude decimal(18,8),
	Longitude decimal(18,8)
);




CREATE TABLE HMDApub2012
(
	AsOfDate varchar(4),
	RespondentID varchar(10),
	RespondentName varchar(60),
	AgencyCode varchar(1),
	LoanType varchar(1),
	PropertyType varchar(1),
	LoanPurpose varchar(1),
	Occupancy varchar(1),
	LoanAmount varchar(8),
	Preapproval varchar(1),
	ActionType varchar(1),
	MSAOfProperty varchar(5),
	StateCode varchar(2),
	StateName varchar(20),
	CountyCode varchar(3),
	CountyName varchar(50),
	CensusTractNumber varchar(7),
	ApplicantEthnicity varchar(1),
	Co_ApplicantEthnicity varchar(1),
	ApplicantRace1 varchar(1),
	ApplicantRace2 varchar(1),
	ApplicantRace3 varchar(1),
	ApplicantRace4 varchar(1),
	ApplicantRace5 varchar(1),
	CoApplicantRace1 varchar(1),
	CoApplicantRace2 varchar(1),
	CoApplicantRace3 varchar(1),
	CoApplicantRace4 varchar(1),
	CoApplicantRace5 varchar(1),
	ApplicantSex varchar(1),
	CoApplicantSex varchar(1),
	ApplicantIncome varchar(4),
	PurchaserType varchar(1),
	DenialReason1 varchar(1),
	DenialReason2 varchar(1),
	DenialReason3 varchar(1),
	RateSpread varchar(5),
	HOEPAStatus varchar(1),
	LienStatus varchar(1),
	SequenceNumber varchar(10),
	AreaPopulation varchar(10),
	MinorityPopulationPct varchar(6),
	FFIEC_Median_Family_Income varchar(8),
	Tract_to_MSA_MD_Income varchar(6),
	Num_of_Owner_occupied_units varchar(8),
	Num_of_1_to_4_Family_units varchar(8),
	Application_Date_Indicator varchar(1),
	FipsCode varchar(12),
	Latitude decimal(18,8),
	Longitude decimal(18,8)
);

CREATE TABLE HMDApub2013
(
	AsOfDate varchar(4),
	RespondentID varchar(10),
	RespondentName varchar(60),
	AgencyCode varchar(1),
	LoanType varchar(1),
	PropertyType varchar(1),
	LoanPurpose varchar(1),
	Occupancy varchar(1),
	LoanAmount varchar(8),
	Preapproval varchar(1),
	ActionType varchar(1),
	MSAOfProperty varchar(5),
	StateCode varchar(2),
	StateName varchar(20),
	CountyCode varchar(3),
	CountyName varchar(50),
	CensusTractNumber varchar(7),
	ApplicantEthnicity varchar(1),
	CoApplicantEthnicity varchar(1),
	ApplicantRace1 varchar(1),
	ApplicantRace2 varchar(1),
	ApplicantRace3 varchar(1),
	ApplicantRace4 varchar(1),
	ApplicantRace5 varchar(1),
	CoApplicantRace1 varchar(1),
	CoApplicantRace2 varchar(1),
	CoApplicantRace3 varchar(1),
	CoApplicantRace4 varchar(1),
	CoApplicantRace5 varchar(1),
	ApplicantSex varchar(1),
	CoApplicantSex varchar(1),
	ApplicantIncome varchar(4),
	PurchaserType varchar(1),
	DenialReason1 varchar(1),
	DenialReason2 varchar(1),
	DenialReason3 varchar(1),
	RateSpread varchar(5),
	HOEPAStatus varchar(1),
	LienStatus varchar(1),
	SequenceNumber varchar(10),
	AreaPopulation varchar(10),
	MinorityPopulationPct varchar(6),
	FFIEC_Median_Family_Income varchar(8),
	Tract_to_MSA_MD_Income varchar(6),
	Num_of_Owner_occupied_units varchar(8),
	Num_of_1_to_4_Family_units varchar(8),
	Application_Date_Indicator varchar(1),
	FipsCode varchar(12),
	Latitude decimal(18,8),
	Longitude decimal(18,8)
);







